<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $soal = [
            // ================= MATEMATIKA (Soal 1 - 17) =================
            [
                'question_text' => 'Hasil dari -15 + 20 - 5 adalah...',
                'option_a' => '-10',
                'option_b' => '0',
                'option_c' => '10',
                'option_d' => '-5',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Jika 3x - 5 = 10, maka nilai x adalah...',
                'option_a' => '3',
                'option_b' => '5',
                'option_c' => '7',
                'option_d' => '10',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Nilai dari 5^2 - 3^2 adalah...',
                'option_a' => '16',
                'option_b' => '14',
                'option_c' => '22',
                'option_d' => '8',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'FPB dari 24 dan 36 adalah...',
                'option_a' => '6',
                'option_b' => '8',
                'option_c' => '12',
                'option_d' => '18',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'KPK dari 4, 6, dan 8 adalah...',
                'option_a' => '12',
                'option_b' => '16',
                'option_c' => '24',
                'option_d' => '32',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Hasil dari 3/4 + 2/5 adalah...',
                'option_a' => '5/9',
                'option_b' => '23/20',
                'option_c' => '5/20',
                'option_d' => '11/20',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Keliling persegi panjang dengan panjang 12 cm dan lebar 8 cm adalah...',
                'option_a' => '20 cm',
                'option_b' => '40 cm',
                'option_c' => '96 cm',
                'option_d' => '48 cm',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Luas segitiga dengan alas 10 cm dan tinggi 6 cm adalah...',
                'option_a' => '60 cm²',
                'option_b' => '30 cm²',
                'option_c' => '16 cm²',
                'option_d' => '36 cm²',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Volume kubus dengan rusuk 5 cm adalah...',
                'option_a' => '25 cm³',
                'option_b' => '75 cm³',
                'option_c' => '125 cm³',
                'option_d' => '150 cm³',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Jika rasio dua bilangan adalah 3:5 dan jumlahnya 40, bilangan terkecil adalah...',
                'option_a' => '10',
                'option_b' => '15',
                'option_c' => '20',
                'option_d' => '25',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Gradien dari garis yang melalui titik (2, 3) dan (4, 7) adalah...',
                'option_a' => '1',
                'option_b' => '2',
                'option_c' => '3',
                'option_d' => '4',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Nilai rata-rata dari data 5, 7, 8, 6, 9 adalah...',
                'option_a' => '6',
                'option_b' => '7',
                'option_c' => '8',
                'option_d' => '9',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Hasil dari √144 adalah...',
                'option_a' => '11',
                'option_b' => '12',
                'option_c' => '13',
                'option_d' => '14',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Penyelesaian dari pertidaksamaan 2x + 3 > 7 adalah...',
                'option_a' => 'x > 2',
                'option_b' => 'x > 3',
                'option_c' => 'x > 4',
                'option_d' => 'x < 2',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Panjang sisi miring segitiga siku-siku dengan sisi 3 cm dan 4 cm adalah...',
                'option_a' => '5 cm',
                'option_b' => '6 cm',
                'option_c' => '7 cm',
                'option_d' => '8 cm',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Hasil dari (2x + 3)(x - 4) adalah...',
                'option_a' => '2x² - 5x - 12',
                'option_b' => '2x² - 8x - 12',
                'option_c' => '2x² + 5x - 12',
                'option_d' => '2x² - 5x + 12',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Jika sin A = 3/5, maka nilai cos A adalah...',
                'option_a' => '3/4',
                'option_b' => '4/5',
                'option_c' => '5/3',
                'option_d' => '4/3',
                'correct_answer' => 'B',
                'points' => 2,
            ],

            // ================= BAHASA INDONESIA (Soal 18 - 34) =================
            [
                'question_text' => 'Kata baku dari kata "aktifitas" adalah...',
                'option_a' => 'Aktifitas',
                'option_b' => 'Aktivitas',
                'option_c' => 'Aktipitas',
                'option_d' => 'Aktivutas',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Penggunaan tanda baca yang tepat terdapat pada kalimat...',
                'option_a' => 'Ibu pergi ke pasar membeli buah, sayur, dan ikan.',
                'option_b' => 'Ibu pergi ke pasar membeli buah sayur dan ikan.',
                'option_c' => 'Ibu pergi ke pasar, membeli buah, sayur, dan, ikan.',
                'option_d' => 'Ibu pergi ke pasar membeli buah; sayur; dan ikan.',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Kata "berlari" dalam kalimat "Anak itu berlari cepat" berfungsi sebagai...',
                'option_a' => 'Subjek',
                'option_b' => 'Predikat',
                'option_c' => 'Objek',
                'option_d' => 'Keterangan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Sinonim dari kata "gundah" adalah...',
                'option_a' => 'Senang',
                'option_b' => 'Resah',
                'option_c' => 'Tenang',
                'option_d' => 'Marah',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Antonim dari kata "mandiri" adalah...',
                'option_a' => 'Bebas',
                'option_b' => 'Otonom',
                'option_c' => 'Bergantung',
                'option_d' => 'Kuat',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Kalimat yang termasuk kalimat majemuk setara adalah...',
                'option_a' => 'Ayah membaca koran sementara ibu memasak.',
                'option_b' => 'Siswa yang rajin pasti berhasil.',
                'option_c' => 'Dia pergi karena hujan turun.',
                'option_d' => 'Budi belajar agar mendapat nilai bagus.',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Majas yang membandingkan dua hal secara langsung disebut...',
                'option_a' => 'Metafora',
                'option_b' => 'Personifikasi',
                'option_c' => 'Hiperbola',
                'option_d' => 'Simile',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Kata yang berakhiran -an dalam kalimat "Dia mengambilkan buku" berfungsi sebagai...',
                'option_a' => 'Kata kerja aktif',
                'option_b' => 'Kata benda',
                'option_c' => 'Kata sifat',
                'option_d' => 'Kata keterangan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Teks yang bertujuan menjelaskan suatu proses terjadinya fenomena alam disebut teks...',
                'option_a' => 'Deskripsi',
                'option_b' => 'Eksposisi',
                'option_c' => 'Eksplanasi',
                'option_d' => 'Argumentasi',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Penggunaan kata depan yang tepat terdapat pada kalimat...',
                'option_a' => 'Saya berangkat ke sekolah dengan jalan kaki.',
                'option_b' => 'Saya berangkat ke sekolah dengan berjalan kaki.',
                'option_c' => 'Saya berangkat ke sekolah pada jalan kaki.',
                'option_d' => 'Saya berangkat ke sekolah di jalan kaki.',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Imbuhan peN-...-an pada kata "pendidikan" bermakna...',
                'option_a' => 'Proses',
                'option_b' => 'Hasil',
                'option_c' => 'Tempat',
                'option_d' => 'Alat',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kalimat persuasif bertujuan untuk...',
                'option_a' => 'Menghibur pembaca',
                'option_b' => 'Meyakinkan pembaca',
                'option_c' => 'Menjelaskan sesuatu',
                'option_d' => 'Menceritakan kejadian',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kesalahan dalam penulisan kata depan terdapat pada...',
                'option_a' => 'Berada di rumah',
                'option_b' => 'Pergi ke pasar',
                'option_c' => 'Tiba di Jakarta',
                'option_d' => 'Berlayar di Pulau Jawa',
                'correct_answer' => 'D',
                'points' => 2,
            ],
            [
                'question_text' => 'Amanat dalam cerita fabel "Si Kancil dan Petani" umumnya mengajarkan tentang...',
                'option_a' => 'Kecerobohan berakibat fatal',
                'option_b' => 'Kecerdasan mengalahkan kekuatan',
                'option_c' => 'Kerja keras membawa hasil',
                'option_d' => 'Kesabaran adalah kunci keberhasilan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kalimat yang menggunakan kata sifat dengan benar adalah...',
                'option_a' => 'Harganya sangat mahal sekali.',
                'option_b' => 'Harganya sangat mahal.',
                'option_c' => 'Harganya mahal sekali sekali.',
                'option_d' => 'Harganya paling sangat mahal.',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Unsur intrinsik cerpen yang menunjukkan latar waktu dan tempat disebut...',
                'option_a' => 'Tema',
                'option_b' => 'Penokohan',
                'option_c' => 'Setting',
                'option_d' => 'Sudut pandang',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Dalam surat resmi, salam pembuka yang tepat adalah...',
                'option_a' => 'Halo, apa kabar?',
                'option_b' => 'Dengan hormat,',
                'option_c' => 'Assalamualaikum wr. wb.',
                'option_d' => 'Salam sejahtera untuk kita semua,',
                'correct_answer' => 'B',
                'points' => 2,
            ],

            // ================= ILMU PENGETAHUAN ALAM (IPA) (Soal 35 - 50) =================
            [
                'question_text' => 'Organel sel yang berfungsi sebagai pusat pengendali sel adalah...',
                'option_a' => 'Mitokondria',
                'option_b' => 'Membran sel',
                'option_c' => 'Inti sel (Nukleus)',
                'option_d' => 'Ribosom',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Perubahan wujud dari gas menjadi cair disebut...',
                'option_a' => 'Menguap',
                'option_b' => 'Mengembun',
                'option_c' => 'Menyublim',
                'option_d' => 'Membeku',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Satuan gaya dalam sistem Internasional (SI) adalah...',
                'option_a' => 'Kilogram',
                'option_b' => 'Newton',
                'option_c' => 'Pascal',
                'option_d' => 'Joule',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Hukum Newton ke-3 berbunyi tentang aksi-reaksi, yang bermakna...',
                'option_a' => 'Setiap aksi memiliki reaksi yang sama besar dan berlawanan arah',
                'option_b' => 'Benda cenderung mempertahankan keadaannya',
                'option_c' => 'Percepatan berbanding lurus dengan gaya',
                'option_d' => 'Energi tidak dapat diciptakan',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Proses fotosintesis menghasilkan...',
                'option_a' => 'Karbondioksida dan air',
                'option_b' => 'Oksigen dan glukosa',
                'option_c' => 'Oksigen dan karbondioksida',
                'option_d' => 'Glukosa dan air',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Contoh perubahan kimia adalah...',
                'option_a' => 'Es mencair',
                'option_b' => 'Gula larut dalam air',
                'option_c' => 'Besi berkarat',
                'option_d' => 'Kertas disobek',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Lapisan atmosfer terdekat dengan bumi tempat cuaca terjadi adalah...',
                'option_a' => 'Stratosfer',
                'option_b' => 'Mesosfer',
                'option_c' => 'Troposfer',
                'option_d' => 'Termosfer',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sistem peredaran darah besar mengalirkan darah dari jantung ke...',
                'option_a' => 'Paru-paru dan kembali ke jantung',
                'option_b' => 'Seluruh tubuh dan kembali ke jantung',
                'option_c' => 'Otak dan kembali ke paru-paru',
                'option_d' => 'Hati dan kembali ke jantung',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Unsur kimia yang simbolnya "Fe" adalah...',
                'option_a' => 'Fluor',
                'option_b' => 'Fosfor',
                'option_c' => 'Besi',
                'option_d' => 'Timah',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'pH larutan asam berada pada rentang...',
                'option_a' => '0 - 6',
                'option_b' => '7',
                'option_c' => '8 - 14',
                'option_d' => '1 - 14',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Tekanan hidrostatis bergantung pada...',
                'option_a' => 'Massa zat dan gravitasi',
                'option_b' =>'Kedalaman dan massa jenis zat cair',
                'option_c' => 'Volume zat cair dan suhu',
                'option_d' => 'Luas penampang dan gaya',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Jaringan tumbuhan yang berfungsi mengangkut air dan nutrisi dari akar ke daun adalah...',
                'option_a' => 'Floem',
                'option_b' => 'Xilem',
                'option_c' => 'Epidermis',
                'option_d' => 'Kambium',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Hewan yang termasuk dalam kelompok mamalia adalah...',
                'option_a' => 'Hiu',
                'option_b' => 'Katak',
                'option_c' => 'Kelelawar',
                'option_d' => 'Penyu',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sifat cahaya yang terjadi pada peristiwa pelangi adalah...',
                'option_a' => 'Pemantulan',
                'option_b' => 'Pembiasan',
                'option_c' => 'Penguraian (Dispersi)',
                'option_d' => 'Interferensi',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sumber energi utama bagi makhluk hidup di bumi adalah...',
                'option_a' => 'Matahari',
                'option_b' => 'Bulan',
                'option_c' => 'Angin',
                'option_d' => 'Air',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Perpindahan panas yang terjadi pada saat kita memasak air dalam panci disebut...',
                'option_a' => 'Konduksi',
                'option_b' => 'Konveksi',
                'option_c' => 'Radiasi',
                'option_d' => 'Isolasi',
                'correct_answer' => 'B',
                'points' => 2,
            ],
        ];

        foreach ($soal as $s) {
            Question::create($s);
        }
    }
}