<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $soal = [
            // ================= BAHASA INDONESIA (1 - 10) =================
            [
                'question_text' => 'Di bawah ini yang termasuk kata baku adalah...',
                'option_a' => 'Aktifitas',
                'option_b' => 'Aktivitas',
                'option_c' => 'Aktifistas',
                'option_d' => 'Aktipitas',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kalimat berikut yang menggunakan tanda koma dengan benar adalah...',
                'option_a' => 'Ibu membeli gula, beras dan minyak.',
                'option_b' => 'Ibu membeli gula beras dan minyak.',
                'option_c' => 'Ibu membeli gula, beras, dan minyak.',
                'option_d' => 'Ibu membeli, gula beras dan minyak.',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sinonim kata "inspirasi" adalah...',
                'option_a' => 'Motivasi',
                'option_b' => 'Aspirasi',
                'option_c' => 'Ide',
                'option_d' => 'Ekspirasi',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Antonim kata "optimis" adalah...',
                'option_a' => 'Pesimis',
                'option_b' => 'Realistis',
                'option_c' => 'Idealistis',
                'option_d' => 'Pragmatis',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => '"Hatinya bagaikan batu yang keras." Majas yang digunakan dalam kalimat tersebut adalah...',
                'option_a' => 'Personifikasi',
                'option_b' => 'Metafora',
                'option_c' => 'Hiperbola',
                'option_d' => 'Simile',
                'correct_answer' => 'D',
                'points' => 2,
            ],
            [
                'question_text' => 'Unsur intrinsik cerita pendek yang berkaitan dengan urutan peristiwa disebut...',
                'option_a' => 'Penokohan',
                'option_b' => 'Alur',
                'option_c' => 'Latar',
                'option_d' => 'Tema',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kata tidak baku dari "karena" adalah...',
                'option_a' => 'Sebab',
                'option_b' => 'Kerena',
                'option_c' => 'Lantaran',
                'option_d' => 'Lantaran sebab',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Teks prosedur bertujuan untuk...',
                'option_a' => 'Menjelaskan langkah-langkah melakukan sesuatu',
                'option_b' => 'Menceritakan pengalaman',
                'option_c' => 'Mendeskripsikan suatu benda',
                'option_d' => 'Meyakinkan pembaca',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Kalimat utama dalam sebuah paragraf biasanya terletak di...',
                'option_a' => 'Akhir paragraf',
                'option_b' => 'Tengah paragraf',
                'option_c' => 'Awal atau akhir paragraf',
                'option_d' => 'Setiap kalimat',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => '"Angin berbisik di malam yang sunyi." Kalimat tersebut mengandung majas...',
                'option_a' => 'Metafora',
                'option_b' => 'Personifikasi',
                'option_c' => 'Litotes',
                'option_d' => 'Metonimia',
                'correct_answer' => 'B',
                'points' => 2,
            ],

            // ================= BAHASA INGGRIS (11 - 20) =================
            [
                'question_text' => '"She ___ to school every day." Kata yang tepat untuk melengkapi kalimat tersebut adalah...',
                'option_a' => 'go',
                'option_b' => 'goes',
                'option_c' => 'going',
                'option_d' => 'went',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'The opposite of "cheap" is...',
                'option_a' => 'Expensive',
                'option_b' => 'Wide',
                'option_c' => 'Small',
                'option_d' => 'Narrow',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => '"I have ___ finished my homework." Kata yang tepat adalah...',
                'option_a' => 'yet',
                'option_b' => 'already',
                'option_c' => 'still',
                'option_d' => 'ever',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'They ___ playing football when it started to rain.',
                'option_a' => 'is',
                'option_b' => 'are',
                'option_c' => 'was',
                'option_d' => 'were',
                'correct_answer' => 'D',
                'points' => 2,
            ],
            [
                'question_text' => '"My book is ___ than yours." Kata yang tepat adalah...',
                'option_a' => 'more thick',
                'option_b' => 'thicker',
                'option_c' => 'thickest',
                'option_d' => 'most thick',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'What is the correct spelling of the number 100 in English?',
                'option_a' => 'One hundred',
                'option_b' => 'One hundredth',
                'option_c' => 'One hundreds',
                'option_d' => 'A hundredth',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => '"Would you like ___ coffee?" Kata yang tepat adalah...',
                'option_a' => 'some',
                'option_b' => 'many',
                'option_c' => 'few',
                'option_d' => 'a few',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'The teacher said, "Please ___ attention to the explanation."',
                'option_a' => 'make',
                'option_b' => 'give',
                'option_c' => 'pay',
                'option_d' => 'take',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Arti dari kalimat "I look forward to hearing from you" adalah...',
                'option_a' => 'Saya menyesal mendengarnya',
                'option_b' => 'Saya menantikan kabar dari Anda',
                'option_c' => 'Saya senang bertemu Anda',
                'option_d' => 'Saya ingin melihat Anda',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => '"If it rains, I ___ stay at home." Kata yang tepat adalah...',
                'option_a' => 'will',
                'option_b' => 'would',
                'option_c' => 'am',
                'option_d' => 'do',
                'correct_answer' => 'A',
                'points' => 2,
            ],

            // ================= IPA (21 - 30) =================
            [
                'question_text' => 'Organel sel yang berfungsi sebagai tempat respirasi seluler adalah...',
                'option_a' => 'Nukleus',
                'option_b' => 'Mitokondria',
                'option_c' => 'Ribosom',
                'option_d' => 'Lisosom',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Perubahan wujud dari cair menjadi padat disebut...',
                'option_a' => 'Mencair',
                'option_b' => 'Menguap',
                'option_c' => 'Membeku',
                'option_d' => 'Menyublim',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Satuan tekanan dalam SI adalah...',
                'option_a' => 'Newton',
                'option_b' => 'Joule',
                'option_c' => 'Pascal',
                'option_d' => 'Watt',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Planet terbesar dalam tata surya adalah...',
                'option_a' => 'Saturnus',
                'option_b' => 'Jupiter',
                'option_c' => 'Neptunus',
                'option_d' => 'Uranus',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Bagian mata yang berfungsi untuk mengatur jumlah cahaya yang masuk adalah...',
                'option_a' => 'Lensa',
                'option_b' => 'Retina',
                'option_c' => 'Iris',
                'option_d' => 'Kornea',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Contoh perubahan fisika adalah...',
                'option_a' => 'Kayu terbakar',
                'option_b' => 'Buah membusuk',
                'option_c' => 'Air mendidih',
                'option_d' => 'Besi berkarat',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Golongan darah yang disebut donor universal adalah...',
                'option_a' => 'A',
                'option_b' => 'B',
                'option_c' => 'AB',
                'option_d' => 'O',
                'correct_answer' => 'D',
                'points' => 2,
            ],
            [
                'question_text' => 'Gerak bumi mengelilingi matahari disebut...',
                'option_a' => 'Rotasi',
                'option_b' => 'Revolusi',
                'option_c' => 'Presesi',
                'option_d' => 'Nutasi',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Zat berikut yang bersifat asam adalah...',
                'option_a' => 'Sabun',
                'option_b' => 'Pasta gigi',
                'option_c' => 'Cuka',
                'option_d' => 'Kapur',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Jenis sendi yang memungkinkan gerakan ke segala arah adalah sendi...',
                'option_a' => 'Engsel',
                'option_b' => 'Pelana',
                'option_c' => 'Peluru',
                'option_d' => 'Putar',
                'correct_answer' => 'C',
                'points' => 2,
            ],

            // ================= IPS (31 - 40) =================
            [
                'question_text' => 'Kerajaan Hindu tertua di Indonesia adalah...',
                'option_a' => 'Sriwijaya',
                'option_b' => 'Majapahit',
                'option_c' => 'Kutai',
                'option_d' => 'Tarumanegara',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sumber daya alam yang tidak dapat diperbarui adalah...',
                'option_a' => 'Air',
                'option_b' => 'Minyak bumi',
                'option_c' => 'Hutan',
                'option_d' => 'Angin',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Garis khayal yang membagi bumi menjadi belahan utara dan selatan adalah...',
                'option_a' => 'Garis bujur',
                'option_b' => 'Garis lintang',
                'option_c' => 'Garis khatulistiwa',
                'option_d' => 'Garis batas internasional',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Tokoh yang memproklamasikan kemerdekaan Indonesia adalah...',
                'option_a' => 'Soekarno dan Hatta',
                'option_b' => 'Soekarno dan Syahrir',
                'option_c' => 'Hatta dan Tan Malaka',
                'option_d' => 'Soeharto dan Hatta',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Kegiatan menyalurkan barang dari produsen ke konsumen disebut...',
                'option_a' => 'Produksi',
                'option_b' => 'Distribusi',
                'option_c' => 'Konsumsi',
                'option_d' => 'Koleksi',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Benua terluas di dunia adalah...',
                'option_a' => 'Afrika',
                'option_b' => 'Amerika',
                'option_c' => 'Asia',
                'option_d' => 'Eropa',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Sistem tanam paksa pada masa penjajahan Belanda disebut...',
                'option_a' => 'Rodi',
                'option_b' => 'Cultuurstelsel',
                'option_c' => 'Politik Etis',
                'option_d' => 'Devide et Impera',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Batas wilayah laut Indonesia yang diukur dari garis dasar sejauh 200 mil disebut...',
                'option_a' => 'Zona Ekonomi Eksklusif',
                'option_b' => 'Laut Teritorial',
                'option_c' => 'Landas Kontinen',
                'option_d' => 'Perairan Nusantara',
                'correct_answer' => 'A',
                'points' => 2,
            ],
            [
                'question_text' => 'Mata pencaharian utama penduduk di daerah pegunungan adalah...',
                'option_a' => 'Nelayan',
                'option_b' => 'Petani',
                'option_c' => 'Pedagang',
                'option_d' => 'Pertambangan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Organisasi perdagangan dunia yang mengatur tata niaga internasional adalah...',
                'option_a' => 'IMF',
                'option_b' => 'World Bank',
                'option_c' => 'WTO',
                'option_d' => 'ASEAN',
                'correct_answer' => 'C',
                'points' => 2,
            ],

            // ================= PPKN (41 - 50) =================
            [
                'question_text' => 'Pancasila sebagai dasar negara tercantum dalam Pembukaan UUD 1945 pada alinea ke...',
                'option_a' => 'I',
                'option_b' => 'II',
                'option_c' => 'III',
                'option_d' => 'IV',
                'correct_answer' => 'D',
                'points' => 2,
            ],
            [
                'question_text' => 'Bunyi sila ke-4 Pancasila adalah...',
                'option_a' => 'Persatuan Indonesia',
                'option_b' => 'Keadilan sosial bagi seluruh rakyat Indonesia',
                'option_c' => 'Kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan perwakilan',
                'option_d' => 'Kemanusiaan yang adil dan beradab',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Lembaga negara yang memiliki kewenangan mengubah dan menetapkan UUD adalah...',
                'option_a' => 'DPR',
                'option_b' => 'MPR',
                'option_c' => 'DPD',
                'option_d' => 'Presiden',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Hak asasi manusia yang dijamin dalam UUD 1945 pasal 28A adalah hak untuk...',
                'option_a' => 'Bekerja',
                'option_b' => 'Hidup',
                'option_c' => 'Berserikat',
                'option_d' => 'Mendapatkan pendidikan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Kewajiban warga negara Indonesia yang diatur dalam UUD 1945 pasal 27 ayat (3) adalah...',
                'option_a' => 'Membayar pajak',
                'option_b' => 'Mengikuti pendidikan dasar',
                'option_c' => 'Ikut serta dalam upaya bela negara',
                'option_d' => 'Menghormati hak asasi orang lain',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Semboyan "Bhinneka Tunggal Ika" berasal dari kitab...',
                'option_a' => 'Negarakertagama',
                'option_b' => 'Sutasoma',
                'option_c' => 'Arjunawiwaha',
                'option_d' => 'Bharatayudha',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Bentuk negara Indonesia adalah...',
                'option_a' => 'Serikat',
                'option_b' => 'Kesatuan',
                'option_c' => 'Konfederasi',
                'option_d' => 'Monarki',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Pemilihan umum di Indonesia dilaksanakan setiap...',
                'option_a' => '3 tahun',
                'option_b' => '4 tahun',
                'option_c' => '5 tahun',
                'option_d' => '6 tahun',
                'correct_answer' => 'C',
                'points' => 2,
            ],
            [
                'question_text' => 'Lembaga yang berwenang melakukan uji materil terhadap undang-undang adalah...',
                'option_a' => 'Mahkamah Agung',
                'option_b' => 'Mahkamah Konstitusi',
                'option_c' => 'Komisi Yudisial',
                'option_d' => 'Badan Pemeriksa Keuangan',
                'correct_answer' => 'B',
                'points' => 2,
            ],
            [
                'question_text' => 'Contoh sikap yang sesuai dengan sila ke-3 Pancasila adalah...',
                'option_a' => 'Menghormati teman yang berbeda agama',
                'option_b' => 'Mengutamakan musyawarah dalam mengambil keputusan',
                'option_c' => 'Bangga menggunakan produk dalam negeri',
                'option_d' => 'Memberi bantuan kepada korban bencana alam',
                'correct_answer' => 'C',
                'points' => 2,
            ],
        ];

        foreach ($soal as $s) {
            Question::create($s);
        }
    }
}
